from datetime import datetime
import numpy as np
import pandas as pd
from .star.star_common import CIF
from .star.star_tokenizer import tokenize
from .star.star_parser import parser


class Block:
    def __init__(self,id='default',block_type='star'):
        """
        Empty STAR|mmCIF Datablock
        block_type: 'star' or 'cif'
        """        
        # Init
        if block_type in ['star','cif']:
            self.type = block_type
        # private dict
        self.db = {'db_id': id, 'db_type': block_type}
        # internal structure of a (Data)Block is a dataframe only for STAR 
        self._df = None # Only for STAR file
        self._id = id
        
    def from_dict(self,data):
        if data:
            if self.type == 'star':
                # Create the dataframe
                self._df = self._dataframe(data,self.type)
            self.db = data
            # Get the table(s)
            for k in self.db.keys():
                if isinstance(self.db[k],dict):
                    # We assume this is a table
                    tname = k
                    # Create the table if any
                    t = Table(tname)
                    t.from_data(self.db[tname])
                    self.db[k] = t
            self._id = data['db_id'] if 'db_id' in data else 'default'
    
    @property
    def id(self):
        return self._id
    
    @property
    def db_id(self):
        return self._id
    
    @property
    def df(self):
        if self._df is None:
            self._df = self._dataframe(self.db,self.type)    
        return self._df
    
    @property
    def data(self):
        print(self.db)
        return self.db
    
    @id.setter
    def id(self,blockname):
        self._id = blockname
    
    def get(self,key):
        if key in self.db.keys():
            return self.db[key]
        else:
            return None

    def set(self,key,value):
        self.db[key] = value
        if self._df is not None:
            self._df.loc[:,key] = value
             
    def add(self,tdata,tname = 'table'):
        if self.type == 'star' and tname != 'table':
            return 'ERROR: A table in a STAR file cannot have a name'
        if isinstance(tdata,Table):
            self.db[tname] = tdata
        else:
            t = Table(tname)
            t.from_data(tdata)
            self.db[tname] = t

    def table(self,tname = 'table'):
        if tname in self.db.keys():
            return self.db[tname]
        return None
    
    def _dataframe(self,dic,blcktype):
        print(dic)
        if blcktype == 'star':
            # Merge key/values and table in one single dataframe
            # Each key corresponds to a column of a constant (`value`) 
            if 'table' in dic.keys():
                # Step #1 get the table
                t = Table('table')
                print(dic['table'])
                t.from_data(dic['table'])
                df = t.df
                for key,value in dic.items():
                    if key != 'table':
                        df.loc[:, key] = value
                print(df)
            else:
                df = pd.DataFrame([dic.values()],columns=dic.keys())
            return df
    
    def value_of(self,category,attr='value'):
        return self.db[category][attr]
    
    def to_star(self):
        s = f"data_{self.db_id}\n#\n# File generated by GRINDER the {datetime.now().strftime('%Y-%m-%d at %H:%M')}\n#\n"
        for key in self.db.keys():
            value = self.db[key]
            if key != 'db_id' and key != 'db_type':
                if type(value) is not dict:
                    s += f'_{key:<30} {self.db[key]}\n'
                else:
                    # The value is a table
                    s += '#\nloop_\n'
                    for col in value['columns']:
                        s += f'_{col}\n'
                    for row in value['rows']:
                        for v in row:
                            s += f'{v:<20} '
                        s += '\n'
                    s += '#\n'
        return s

    def to_starfile(self,sf):
        """
        sf: STAR file
        """
        s = f"data_{self.db_id}\n#\n"
        sf.write(s)
        for key in self.db.keys():
            value = self.db[key]
            if key != 'db_id' and key != 'db_type':
                if type(value) is not dict:
                    sf.write(f'_{key:<30} {self.db[key]}\n')
                else:
                    # The value is a table
                    sf.write('#\nloop_\n')
                    for col in value['columns']:
                        sf.write( f'_{col}\n')
                    for row in value['rows']:
                        for v in row:
                            sf.write(f'{v:<20} ')
                        sf.write('\n')
                    sf.write('#\n')

    def __repr__(self):
        return self.__str__()

    def __str__(self):
        s = f'data_{self.id}\n'
        for k in self.db.keys():
            if k == 'table':
                s += str(self.db['table'])
            else:
                s+= f'{k} {self.db[k]}\n'
        return s

class Table:
    def __init__(self,tname = 'table'):
        """
        Create an empty table entitled `tname`
        """
        self._id = tname
        
    def from_data(self,data=None,*,columns=None):
        if isinstance(data,dict):
            self.df = pd.DataFrame(data['rows'],columns=data['columns'])
        else:
            self.df = pd.DataFrame(data=data, columns=columns)
    
    # def from_dict(self,dict):
    #     self.df = pd.DataFrame(dict,index=[0])

    def columns(self):
        return self.df.columns
    
    def rows(self):
        return self.df.data

    def dataframe(self,colindex=0):
        """
        Obsolete?
        """
        # creating DataFrame
        df = pd.DataFrame(self.table['data'], columns=self.table['columns'])
        df.set_index(self.table['columns'][colindex],inplace=True,drop=False)
        return df
        
    def loc(self,irow,icol=None):
        return self.df.iloc[irow] if icol == None else self.df.iloc[irow,icol]
    
    def row(self,i):
        return self.df.iloc[i]
    
    def append(self,row):
        """
        Append a row in this table. The row can be a Dictionary or a List
        """
        if isinstance(row,dict):
            self.df.loc[self.df.shape[0]] = row
        elif isinstance(row,list):
            self.df.loc[self.df.shape[0]] = row
        else:
            print('ERROR: Not supported')
        # Remove duplicates if any
        self.df = self.df.drop_duplicates().reset_index(drop=True)
    
    def concat(self,rows):
        """
        Append several rows in this table. The rows can be a `list[dict]` or `list[list]`
        """
        if isinstance(rows[0],dict):
            row_df = pd.DataFrame(rows)
        elif isinstance(rows[0],list):
            row_df = pd.DataFrame(rows, columns=list(self.df.columns))
        else:
            print('ERROR: Not supported')
            return
        self.df = pd.concat([self.df,row_df], ignore_index=True)
        # Remove duplicates if any
        self.drop = self.df.drop_duplicates().reset_index(drop=True)
    
    def column(self,colname):
        """
        Get all the values of the column `colname`. `colname` could be a single string or a list.
        Returns a pandas.Series
        """
        return self.df[colname]
    
    def to_dict(self,orient='split'):
        if orient in ['dict' , 'list', 'series', 'split', 'tight', 'records', 'index']:
            return self.df.to_dict(orient)
                
    def __repr__(self):
        return self.df.__str__()

    # def __str__(self):
    #     s = '#\nloop_\n'
    #     for h in self.df.columns:
    #         s += f'{h}\n'
    #     for row in self.df.values:
    #         s += ' '.join([d for d in row]) + '\n'
    #     s += '#\n'
    #     return s
    
class StarGate:
    """
    Create an empty StarGate consisting of a collection of DataBlock
    """
    def __init__(self):
        self.db = {} # Dictionary of Block

    @property
    def blocks(self):
        return self.db
    
    def add(self,block):
        self.db[block.id] = block

    def read(self,filename):
        with open(filename) as f:
            self.parseSTAR(f.read()) 
    
    def parse(self,data):
        self.parseSTAR(data) 
    
    def save(self,filename,orient='split'):
        """
        Save blocks as Dictionary containing key/value and/or table
        block = {
            'key': value,
            'table' : {
                'rows|data': [..],
                'columns' : [..]
            }
        }
        orient : Determines the type of the values of the dictionary.
        'dict' (default) : dict like {column -> {index -> value}}
        'list' : dict like {column -> [values]}
        'series' : dict like {column -> Series(values)}
        'split' : dict like {'index' -> [index], 'columns' -> [columns], 'data' -> [values]}
        'tight' : dict like {'index' -> [index], 'columns' -> [columns], 'data' -> [values], 'index_names' -> [index.names], 'column_names' -> [column.names]}
        'records' : list like [{column -> value}, … , {column -> value}]
        'index' : dict like {index -> {column -> value}}

        """
        with open(filename,'w') as f:
            pass
        with open(filename,'a') as f:
            f.write(f"#\n# File generated by StarGate the {datetime.now().strftime('%Y-%m-%d at %H:%M')}\n#\n\n")
            for block in self.db.values():
                block.to_starfile(f)
                f.write("\n\n")
        return 'Done!'
    
    def save_tables(self,blocks,filename):
        """
            Save blocks as Dictionary of Dataframes
            block =  pd.DataFrame
        """
        with open(filename,'a') as f:
            for blockid in blocks.keys():
                txt = self._dataframe_to_string(blocks[blockid],blockid)
                f.write(txt)
    
    def datablock(self,blockname=None):
        if blockname is None:
            b = next(iter(self.db))
            return b # Block(b)
        # if blockname set
        for bn in self.db.keys():
            if bn == blockname:
                return self.db[bn] # Block(self.db[bn])
        return None
    
    def table_of(self,blockname):
        for db in self.db['datablocks']:
            if db['id'] == blockname and db['table']:
                return db
        return None
    
    def parseSTAR(self,txt):
        # First Pass
        tokens = tokenize(txt)
        # Second Pass - Parse
        blocks = parser(tokens)
        for bid,b in blocks.items():
            print('create block:',bid)
            blck = Block(bid)
            blck.from_dict(b)
            self.add(blck)

    def to_json(self):
        """
        Build JSON object from StarGate datablocks
        """
        d = self.db # Datablocks
        for k, v in d.items():
            if isinstance(v, pd.DataFrame):
                d[k] = v.T.to_dict(orient='split')
            elif type(v) is dict:
                d[k] = self.to_json(v)
        return d
    
    def to_object(self,mmcif=False):
        def obj_dic(d):
            top = type('new', (object,), d)
            seqs = (tuple, list, set, frozenset)
            for i, j in d.items():
                if isinstance(j, dict):
                    setattr(top, i, obj_dic(j))
                elif isinstance(j, seqs):
                    setattr(top, i, 
                        type(j)(obj_dic(sj) if isinstance(sj, dict) else sj for sj in j))
                else:
                    setattr(top, i, j)
            return top
       
        # Main
        if mmcif:
            id = next(iter(self.db))
            return obj_dic(self.db[id])
        else:
            return obj_dic(self.db)

    def _block_to_string(self,block,blockid):
        # Create input star file
        msg = f'data_{blockid}\n#\n'
        for key in block.keys():
            if key == 'table':
                msg +='loop_\n'
                for i,k in enumerate(block['table']['columns']):
                    spc = ' ' * (30 - len(k))
                    msg += f'_spr{k}{spc}#{i+1}\n'
                # Check if key `data` from dataframe.to_dict()
                rows = 'data' if 'data' in block['table'] else 'rows'
                for row in block['table'][rows]:
                    for v in row:
                        if type(v) is str and len(v.split()) > 1:
                            msg += f'\'{v}\'  '
                        else:
                            msg += f'{v}  '
                    msg += '\n'
                msg += '\n#\n'
            else:
                spc = ' ' * (30 - len(key))
                if type(block[key]) == str and len(block[key].split()) > 1:
                    msg += f'_{key}{spc}\'{block[key]}\'\n'
                else:
                    msg += f'_{key}{spc}{block[key]}\n'
        msg += f'\n# End of datablock {blockid}\n\n'
        return msg
        
    def _dataframe_to_string(self,block,blockid):
        # Create input star file
        msg = f'data_{blockid}\n\n'
        msg +='loop_\n'
        # Write headings
        for i,k in enumerate(block.columns):
                spc = ' ' * (30 - len(k))
                msg += f'_spr{k}{spc}#{i+1}\n'
        # Write rows
        for i in range(block.shape[0]):
            row = block.iloc[i, :].values.flatten().tolist()
            for v in row:
                if type(v) is str and len(v.split()) > 1:
                    msg += f'\'{v}\'  '
                else:
                    msg += f'{v}  ' 
            msg += '\n'
        msg += '#\n'

        msg += f'\n# End of datablock {blockid}\n\n'
        return msg

    def __repr__(self):
        return self.__str__()

    def __str__(self):
        s = ''
        for blck in self.db.values():
            s += str(blck)
        return s
    
